const messages = {
    en: {
        nav: {
            home: 'Home',
            whatispigy: 'What is PIGY',
            token: 'Tokenomics',
            spo: 'SPO',
            roadmap: 'Roadmap',
            faq: 'FAQ',
            aboutus: 'About us',
        },
        home: {
            head: 'The Community-Driven Token for Cardano Stake-Pool-Operators and Delegators',
            text: 'We support Cardano decentralization program. PIGY Token is a Cardano based cryptocurrency that distributed by SPO as additional rewards to delegators',
            button: 'What is PIGY',
            button_buy: 'BUY',
            divider: 'The autonomy of the network can only be given by an absolutely decentralized network. That´s why Pigy Token wants to serve as an additional tool for small stake pools.',
            divider_p: '- A Pigy Token Member',
        },
        whatispigy: {
            head: 'What is PIGY Token',
            text: 'PIGY Token—which was built on the Cardano crypto-currency blockchain—is currently being distributed by SPO as special rewards to delegators. PIGY Token strengthens the Cardano ecosystem by supporting the delegators to the smaller stake pools that are the backbone of decentralization and integrity.',
            text_2: 'Cardano is a crypto-currency project that was launched in 2015 in a bid to revise the process through which cryptocurrencies were produced and developed. The big idea, which is beyond just changing the way cryptocurrencies are produced, is to create a better, more conducive ecosystem in the cryptocurrency world through a comprehensive roadmap, a collection of thorough design principles, engineering best practices and avenues for exploration that better account for the needs of its users. There are around 2,600 Stake Pool Operators right now. Over 30% of these operators have never minted a single block, which translates to about 1,000 of them. Cardano Foundation and IOG are currently doing their best to ensure the operators of small pools survive, but they only have a limited amount of resources. We as a community can help these blockless stake pools by giving incentives so the delegators are willing to move around to a smaller pool and keep moving around the pools so that it will help the small pools survive.',
            button: 'Go to White Paper',
            divider: 'A pig’s tail will never make a good arrow.',
            divider_p: '- French proverb',
        },
        token: {
            head: 'Tokenomics',
            text_supply_head: '$ SUPPLY',
            text_supply:
                'The supply of PIGY Token is locked and limited to only 100,000,000,000 tokens. That means there will be no more minting or burning after those tokens are minted. The purpose of this is to avoid constant inflation of the token which comes as a result of an unlimited supply of token and causes price to drop.',
            text_distributor_head: '$ DISTRIBUTOR',
            text_distributor: 'PIGY Token is obtained from Stake Pool Operators that you delegate your ADA for free. Terms and conditions apply.',
            text_buy_head: '$ BUY',
            text_buy: 'As soon as the Alonzo mainnet goes live on Cardano we will be listed on SWAP / Exchanges. We will keep you up to date!',
            text_airdrop_head: '$ Token Airdrop',
            text_airdrop:
                'We are distributing a total of 25,000,000,000 PIGY tokens to all stake pool operators who register with us. If you are a pool operator and would like to receive PIGY Tokens, please register via our form. You will then receive a one-time payment of 10,000,000 PIGY.',
            divider: 'I think my pig is whistling!',
            divider_p: '- German proverb',
        },
        spo: {
            head: 'SPO',
            text: 'Here you can search for your pool using the search field by entering ticker, if it has received PIGY Token from us you will find it here. Please ask your pool operator how you can get PIGY Token.',
            notice: 'If you are a Stake Pool operator please fill our type form. NOTE: Each pool receives 10 million PIGY tokens only once!',
            notice2: 'You will be redirected to a form at tripetto.app!',
            button: 'Register for SPO',
            divider: 'Kill the middleman of necessity, push power to the edges and build systems that are equally fair for the least amongst us.',
            divider_p: '- Charles Hoskinson',
            pool_count_text_1: 'Over ',
            pool_count_text_2: 'Stake Pools have now receive $PIGY Token.',
            pool_count_text_3: 'We have currently distributed ',
            pool_count_text_4: '$PIGY tokens to Stake Pool operators.',
        },
        roadmap: {
            head: 'Roadmap',
            divider: 'Life is better with Pigs.',
            divider_p: '- Unknown',
            q1: {
                head: '$ Q1 - 2021',
                list_1: '',
            },
            q2: {
                head: '$ Q2 - 2021',
                list_1: 'Announce Project ✓',
                list_2: 'Create White Paper ✓',
                list_3: 'Create Website ✓',
                list_4: 'Distribute Tokens to SPOs (In Progress)',
            },
            q3: {
                head: '$ Q3 - 2021',
                list_1: 'Create DApps e.g. as Oracle Token ✓',
                list_2: 'PIGY Oracle ✓',
                list_3: 'Listing on SWAP (DEX) When Alonzo Fork is Coming',
            },
            q4: {
                head: '$ Q4 - 2021',
                list_1: 'Launching #PIGYGames',
                list_2: 'Listing on Exchanges',
                list_3: 'Partnership Announcements',
            },
        },
        aboutus: {
            head: 'About us',
            text_1: 'Hello, we are the Piggys! We would like to briefly tell you something about us. We are stake pool operators and we have had to grapple with the problem of getting delegators to our small pools. This raise the idea of creating incentives to delegator to move their stake to smaller pool operators. By supporting PIGY Token you also supporting Cardano decentralization program',
            text_2: 'The idea behind Pigy Token initially came about as a joke and was based on an homage to Doge Coin and should not be more than a meme token on the Cardano blockchain (hence the name "DOGECOIN KILLER"). But since we are also aware that we don´t really need another meme token and we don´t want to be part of the Pump & Dump Game, we decided to give it a deeper meaning.',
            text_3: 'Pigy Token took the first steps in the Cardano forum, where it was thought and further developed in the first phases. Since the response was quite high in the community, there were more and more SPOs and programmers and we created our first small service (<a target="_blank" href="https://genetics.pigytoken.com/">Pigy Genetics</a>) and our homepage. Since then we have been growing strongly and are already forging further plans on how we can help the stake pool operators to better establish themselves and counteract the centralization of the Cardano ecosystem.',
            text_4: 'If you want to be part of our team or if you want to use PIGY Token in your own project you can contact us via our social media.',
        },
        social: {
            head: 'Social',
            text: 'Here you can find our social media channels. The Cardano community is looking forward to you!',
        },
        faq: {
            head: 'FAQ',
            question_1: 'How do I get PIGY tokens?',
            answer_1: 'Only stake pool operators can currently take a part of the Airdrop. Ask your SPO if he would like to have PIGY tokens too!',
            question_2: 'Is PIGY a Coin or a Token?',
            answer_2: 'PIGY Token is a Native Token on the Cardano Blockchain. <a target="_blank" href="https://docs.cardano.org/native-tokens/learn">Link</a>',
            question_3: 'I‘m a Stake Pool Operator how to claim my Tokens?',
            answer_3: 'We currently have no way of automatically distributing the tokens.We are planning this feature For the future and as soon as the Alonzo Hartfork has started. Currently you can only apply for the tokens via our form: <a target="_blank" href="https://tripetto.app/run/5ZQ50RRTIE">Register</a>',
            question_4: 'I‘m a Stake Pool Operator what are the cost for claiming my tokens?',
            answer_4: 'In order not to be stuck with the fees, we would ask you to send 2 ADA to the following address. You will get 1.5 ADA back when you receive the PIGY Tokens. You can find out how this works in detail in our form: <a target="_blank" href="https://tripetto.app/run/5ZQ50RRTIE">Register</a>',
            question_5: 'What is PIGY Token?',
            answer_5: 'PIGY Token  is Cardano based cryptocurrency that distrubuted by SPO as additional rewards to delegators',
            question_6: 'How much PIGY that I should give to my delegator?',
            answer_6: 'We are currently not set any amount of how many PIGY that you need to give your delegator. As a help we create each epoch a statistic about all delegators you can find it on the following page. <a target="_blank" href="https://statistics.pigytoken.com">Link</a>',
            question_7: 'How long it will take for me to receive my PIGY after I fill the form?',
            answer_7: 'Usually, it will take about 24 hours except Saturday and Sunday. Currently we still have to do the distribution manually.',
            question_8: 'What happens when the SPO airdrop ends?',
            answer_8: 'To boost the distribution at the beginning we have decided to distribute up to 25B Pigy Tokens to SPOs. After that, we will use analytics to solve the distribution via claiming services. Then, however, few tokens will be distributed to SPOs.',
            question_9: 'Will we create more service around Pigy Token?',
            answer_9: 'Yes. We are working hard on more services for the future, but we have to wait until the Alonzo hardfork is done. Until then, check out our little Pigy Image Game. <a target="_blank" href="https://genetics.pigytoken.com/">Genetics Game</a>',
            question_10: 'You want to join Pigy Token Team?',
            answer_10: 'Then contact us via the usual channels (Mail, Twitter, Discord, Telegram, Github)',
        },
        footer: {
            copyright: '© PIGYToken 2021. All Rights Reserved. ❤️ CARDANO.',
            disclaimer:
                'LEGAL DISCLAIMER: None of the information on this website should be construed as providing legal or financial advice. Please note there are always risks associated with Native Tokens and Smart contracts. Please use at your own risk. PIGYToken is not a registered broker, analyst or investment advisor. If you are willing to, or have purchased PIGYToken, you agree that you are not purchasing a security or investment. The PIGYToken team can not be held liable for any losses or taxes you may incur. You also agree that the team is presenting the token as it was launched, due to it being renounced it can not be changed. Do conduct your own due diligence and consult your financial advisor before making any investment decisions.',
        },
    },
    de: {
        nav: {
            home: 'Home',
            whatispigy: 'Was ist PIGY',
            token: 'Tokenomics',
            spo: 'SPO',
            roadmap: 'Roadmap',
            social: 'Sozial',
            aboutus: 'Über uns',
        },
        home: {
            head: 'Der Community-getriebene Token für Cardano Stake-Pool - Betreiber & Delegatoren',
            text: 'Wir unterstützen das Cardano-Dezentralisierungsprogramm. PIGY Token ist eine auf Cardano basierende Kryptowährung, die von SPO als zusätzliche Belohnung an Delegierte verteilt wird.',
            button: 'Was ist PIGY',
            button_buy: 'BUY',
            divider: 'Die Autonomie des Netzwerks kann nur durch ein absolut dezentrales Netzwerk gegeben sein. Aus diesem Grund möchte Pigy Token als zusätzliches Tool für kleine Stake-Pools dienen.',
            divider_p: '- Ein Team Mitglied',
        },
        whatispigy: {
            head: 'Was ist PIGY Token',
            text: 'PIGY Token – das auf der Cardano-Kryptowährungs-Blockchain basiert – wird derzeit von Stake Pool operatoren als besondere Belohnung an die Delegatoren verteilt. PIGY Token stärkt das Cardano-Ökosystem, indem es die Delegatoren von kleineren Stake-Pools unterstützt, diese bilden das Rückgrat der Dezentralisierung und Integrität.',
            text_2: 'Cardano ist ein Kryptowährungsprojekt, das 2015 mit dem Ziel ins Leben gerufen wurde, den Prozess der Herstellung und Entwicklung von Kryptowährungen zu überarbeiten. Die große Idee, die über die bloße Änderung der Art und Weise, wie Kryptowährungen produziert werden, hinausgeht, besteht darin, ein besseres, förderlicheres Ökosystem in der Welt der Kryptowährungen zu schaffen, und zwar durch eine umfassende Roadmap, eine Sammlung gründlicher Designprinzipien, technischer Best Practices und Möglichkeiten zur Erforschung, die den Bedürfnissen der Nutzer besser Rechnung tragen. Zurzeit gibt es etwa 2.600 Stake-Pool-Betreiber. Mehr als 30 % dieser Betreiber haben noch nie einen einzigen Block gemint, was etwa 1.000 von ihnen ausmacht. Die Cardano Foundation und die IOG tun derzeit ihr Bestes, um das Überleben der Betreiber kleiner Pools zu sichern, aber sie verfügen nur über begrenzte Ressourcen. Wir als Community können diesen blocklosen Stake-Pools helfen, indem wir Anreize schaffen, damit die Delegatoren bereit sind, zu einem kleineren Pool zu wechseln und die Pools weiter zu wechseln, damit die kleinen Pools überleben können.',
            button: 'Weiter zum White Paper',
            divider: 'Aus einem Schweineschwanz wird nie ein guter Pfeil.',
            divider_p: '- Französisches Sprichwort',
        },
        token: {
            head: 'Tokenomics',
            text_supply_head: '$ MENGE',
            text_supply:
                'Die Maximale Anzahl von PIGY Token ist gesperrt und auf nur 100.000.000.000 Token begrenzt. Das bedeutet, dass nach der Prägung dieser Token keine Prägung oder Verbrennung mehr stattfindet. Der Zweck davon ist, eine ständige Inflation des Tokens zu vermeiden, die durch ein unbegrenztes Angebot an Token entsteht und zu einem Preisverfall führt.',
            text_distributor_head: '$ Verteilung',
            text_distributor: 'PIGY Token erhalten Sie von Stake-Pool-Betreibern, an die Sie Ihre ADA delegieren. Bitte achten Sie auf die jeweiliegn Geschäftsbedingungen.',
            text_buy_head: '$ BUY',
            text_buy: 'Sobald das Alonzo Mainnet auf Cardano live geht, werden wir an SWAP / Exchanges gelistet. Wir halten Sie auf dem Laufenden!',
            text_airdrop_head: '$ Token Airdrop',
            text_airdrop:
                'Wir verteilen insgesamt 25.000.000.000 PIGY-Token an alle Stake-Pool-Betreiber, die sich bei uns registrieren. Wenn Sie Poolbetreiber sind und PIGY Tokens erhalten möchten, registrieren Sie sich bitte über unser Formular. Du erhälst dann einmalig 10.000.000 PIGY',
            divider: 'Ich glaube, mein Schwein pfeift!',
            divider_p: '- Deutsches Sprichwort',
        },
        spo: {
            head: 'SPO',
            text: 'Hier können Sie über das Suchfeld durch Eingabe des Tickers nach Ihrem Pool suchen, wenn dieser von uns PIGY Token erhalten hat, finden Sie ihn hier. Bitte fragen Sie Ihren Pool-Betreiber, wie Sie PIGY Token erhalten können.',
            notice: 'Wenn Sie ein Stake-Pool-Betreiber sind, füllen Sie bitte unser Formular aus. NOTE: Each pool receives 10 million PIGY tokens only once!',
            notice2: 'Sie werden zu einem Formular auf tripetto.app weitergeleitet!',
            button: 'Registrieren als SPO',
            divider: 'Töte den Mittelsmann aus der Not, dränge die Macht an den Rand und baue Systeme, die für die Geringsten unter uns gleichermaßen fair sind.',
            divider_p: '- Charles Hoskinson',
            pool_count_text_1: 'Über ',
            pool_count_text_2: 'Stake Pools haben bisher $PIGY Token erhalten.',
            pool_count_text_3: 'Wir haben derzeit ',
            pool_count_text_4: '$PIGY tokens an Stake Pool Betreiber verteilt.',
        },
        roadmap: {
            head: 'Roadmap',
            divider: 'Das Leben ist besser mit Schweinen.',
            divider_p: '- Unknown',
            q1: {
                head: '$ Q1 - 2021',
                list_1: '',
            },
            q2: {
                head: '$ Q2 - 2021',
                list_1: 'Projekt bekanntgabe ✓',
                list_2: 'Whitepaper erstellen ✓',
                list_3: 'Website erstellen ✓',
                list_4: 'Token an SPOs verteilen (in Arbeit)',
            },
            q3: {
                head: '$ Q3 - 2021',
                list_1: 'Auf SWAP Börsen listen (DEX, CEX). Ab Alonzo Fork',
                list_2: 'Find more Use-cases. Z.b. Oracle Fee Token',
                list_3: '#PIGYGames Ankündigung',
            },
            q4: {
                head: '$ Q4 - 2021',
                list_1: 'Starten von #PIGYGames',
                list_2: 'Auflistung an Börsen',
                list_3: 'Partnerschafts-Ankündigungen',
            },
        },
        aboutus: {
            head: 'Über uns',
            text_1: 'Hallo, wir sind die Piggys! Wir möchten Ihnen kurz etwas über uns erzählen. Wir sind Stake-Pool-Betreiber und mussten uns mit dem Problem auseinandersetzen, Delegatoren in unsere kleinen Pools zu bekommen. Dies wirft die Idee auf, Anreize für Delegierende zu schaffen, ihren Anteil an kleinere Poolbetreiber zu verlagern. Durch die Unterstützung von PIGY Token unterstützen Sie auch das Cardano-Dezentralisierungsprogramm ',
            text_2: 'Die Idee hinter Pigy Token entstand anfangs aus einem Spaß und war als eine Hommage an Doge Coin angelehnt und sollte nicht mehr als ein Meme Token auf der Cardano Blockchain sein (Daher auch die Bezeichnung „DOGECOIN KILLER“). Da aber auch uns bewusst ist, dass es nicht wirklich einen weiteren Meme Token braucht und wir kein Teil des Pump & Dump Games sein möchten entschieden wir uns dem ganzen einen tieferen Sinn zu geben.',
            text_3: 'Die ersten Schritte hat Pigy Token im Forum von Cardano gemacht und wurde dort in den ersten Phasen gedacht und weiter ausgearbeitet. Da die Resonanz recht hoch in der Community war fanden sich auch immer mehr SPOs und Programmierer und wir erstellten unseren ersten kleinen Service (Pigy Genetics) und unsere Homepage. Seitdem sind wir stark am Wachsen und schmieden schon an weiteren Plänen wie wir den Stake Pool Operatoren helfen können sich besser zu etablieren und der Zentralisierung des Cardano Ökosystems entgegen zu wirken.',
            text_4: 'Wenn du Teil unseres Teams werden möchtest oder PIGYToken in deinem eigenen Projekt verwenden möchtest, kannst du uns über unsere sozialen Medien kontaktieren.',
        },
        social: {
            head: 'Sozial',
            text: 'Hier finden Sie unsere Social-Media-Kanäle. Wir freuen uns auf dich!',
        },
        faq: {
            head: 'FAQ',
            question_1: 'How do I get $PIGY tokens?',
            answer_1: 'Only stake pool operators can currently take a part of the Airdrop. Ask your SPO if he would like to have $ PIGY tokens too!',
            question_2: 'Is PIGY a Coin or a Token?',
            answer_2: 'Pigy Token is a Native Token on the Cardano Blockchain. <a target="_blank" href="https://docs.cardano.org/native-tokens/learn">Link</a>',
            question_3: 'I‘m a Stake Pool Operator how to claim my Tokens?',
            answer_3: 'We currently have no way of automatically distributing the tokens.We are planning this feature For the future and as soon as the Alonzo Hartfork has started. Currently you can only apply for the tokens via our form: <a target="_blank" href="https://tripetto.app/run/5ZQ50RRTIE">Register</a>',
            question_4: 'I‘m a Stake Pool Operator what are the cost for claiming my tokens?',
            answer_4: 'In order not to be stuck with the fees, we would ask you to send 2 ADA to the following address. You will get 1.5 ADA back when you receive the PIGY Tokens. You can find out how this works in detail in our form: <a target="_blank" href="https://tripetto.app/run/5ZQ50RRTIE">Register</a>',
            question_5: 'What is PIGY Token?',
            answer_5: 'PIGY Token  is Cardano based cryptocurrency that distrubuted by SPO as additional rewards to delegators',
            question_6: 'How much PIGY that I should give to my delegator?',
            answer_6: 'We are currently not set any amount of how many PIGY that you need to give your delegator. As a help we create each epoch a statistic about all delegators you can find it on the following page. <a target="_blank" href="https://statistics.pigytoken.com">Link</a>',
            question_7: 'How long it will take for me to receive my PIGY after I fill the form?',
            answer_7: 'Usually, it will take about 24 hours except Saturday and Sunday. Currently we still have to do the distribution manually.',
            question_8: 'What happens when the SPO airdrop ends?',
            answer_8: 'To boost the distribution at the beginning we have decided to distribute up to 25B Pigy Tokens to SPOs. After that, we will use analytics to solve the distribution via claiming services. Then, however, few tokens will be distributed to SPOs.',
            question_9: 'Will we create more service around Pigy Token?',
            answer_9: 'Yes. We are working hard on more services for the future, but we have to wait until the Alonzo hardfork is done. Until then, check out our little Pigy Image Game. <a target="_blank" href="https://genetics.pigytoken.com/">Genetics Game</a>',
            question_10: 'You want to join Pigy Token Team?',
            answer_10: 'Then contact us via the usual channels (Mail, Twitter, Discord, Telegram, Github)',
        },
        footer: {
            copyright: '© PIGYToken 2021. All Rights Reserved. ❤️ CARDANO.',
            disclaimer:
                'RECHTLICHER HAFTUNGSAUSSCHLUSS: Keine der Informationen auf dieser Website sollte als rechtliche oder finanzielle Beratung verstanden werden. Bitte beachten Sie, dass es immer Risiken gibt, die mit Native Tokens und Smart Contracts verbunden sind. Bitte verwenden Sie diese auf eigenes Risiko. PIGYToken ist kein registrierter Broker, Analyst oder Anlageberater. Wenn Sie PIGYToken kaufen wollen oder gekauft haben, erklären Sie sich damit einverstanden, dass Sie kein Wertpapier oder Investment kaufen. Das PIGYToken-Team kann nicht für etwaige Verluste oder Steuern haftbar gemacht werden, die Ihnen entstehen könnten. Sie erklären sich auch damit einverstanden, dass das Team den Token so präsentiert, wie er eingeführt wurde, da er nicht verändert werden kann. Führen Sie Ihre eigene Due-Diligence-Prüfung durch und konsultieren Sie Ihren Finanzberater, bevor Sie eine Investitionsentscheidung treffen.',
        },
    },
    idn: {
        nav: {
            home: 'Home',
            whatispigy: 'Apa Itu PIGY Token',
            token: 'Tokenomics',
            spo: 'SPO',
            roadmap: 'Roadmap',
            social: 'Social',
            aboutus: 'Tentang Kami',
        },
        home: {
            head: 'Community driven Token untuk Stake- Pool - Operators Dan Delegators',
            text: 'Kami mendukung Cardano desentralisasi program. ',
            button: 'Apa itu PIGY',
            button_buy: 'BELI',
            divider: 'Pigs are smart little creatures. They just need love.',
            divider_p: '- Shelley Duvall',
        },
        whatispigy: {
            head: 'Apa itu PIGY Token',
            text: 'PIGY Token adalah token yang dibuat diatas Cardano Crypto-currency blockchain yang di distribusikan oleh SPO sebagai special rewards untuk para delegators. PIGY Token memperkuat Cardano ecosystem dengan mendukung delegators untuk mendelegasikan ADA nya kepada pool kecil dimana ini merupakan tulang punggung dari desentralisasi dan integritas dari Cardano',
            text_2: 'Cardano adalah crypto-currency project yang diluncurkan pada tahun 2015. Ide besarnya adalah merubah cara bagaimana cryptocurrency diproduksi, untuk menciptakan cryptocurrency yang lebih baik melalui roadmap yang komperhensif, engineering best practices, dan tempat eksplorasi bagi penggunannya. Saat ini ada sekitar 2600 Stake Pool Operator. Lebih dari 30% dari para operator ini belumm pernah membuat sebuah block, atau boleh dikatakan 1,000 dari mereka. Cardano Foundation and IOG berusaha sebaik mungkin agar pool kecil ini dapat selamat, tapi mereka memiliki resource yang sangat terbatas. Kami, komunitas Cardano bisa membantu stake pool yang tanpa block ini dengan memberikan incentives agar para delegator mau untuk memindahkan delegasi nya kepada pool kecil dan pada akhirnya akan menyelamatkan pool kecil ini.',
            button: 'Lihat White Paper',
            divider: 'A pig’s tail will never make a good arrow.',
            divider_p: '- French proverb',
        },
        token: {
            head: 'Tokenomics',
            text_supply_head: '$ SUPPLY',
            text_supply:
                'Supply dari PIGY Token ini dibatasi hanya 100,000,000,000 tokens. Ini artinya PIGY Token ini tidak dapat di produksi lagi ataupun dibakar setelah di-minted. Tujuannya adalah untuk menghindari inflasi dari token yang dikarenakan supply yang tidak terbatas.',
            text_distributor_head: '$ DISTRIBUTOR',
            text_distributor: 'PIGY Token dapat diperoleh melalui Stake Pool Operator secara gratis. *Syarat dan ketentuan berlaku.',
            text_buy_head: '$ BELI',
            text_buy: 'Segera setelah Alonzo mainnet dimulai oleh Cardano, Kami akan segera listing di SWAP / Exchange. Kami akan meng-update kalian!',
            text_airdrop_head: '$ Token Airdrop',
            text_airdrop:
                'Kami mendistribusikan 25,000,000,000 PIGY Token kepada semua Stake Pool Operator yang teregistrasi dengan kami. Kalau anda adalah Stake Pool Operator dan anda menginginkan .',
            divider: 'I think my pig is whistling!',
            divider_p: '- German proverb',
        },
        spo: {
            head: 'SPO',
            text: 'Disini kalian dapat mencari pool mana saja yang memiliki PIGY Token. Silahkan tanya pada pool operator kalian bagaimana kalian dapat mendapat PIGY Token.',
            notice: 'Apabila anda adalah Stake Pool Operator, silahkan isi form ini. NOTE: Setiap pool hanya menerima 10,000,000 PIGY Token sekali!',
            notice2: 'You will be redirected to a form at tripetto.app!',
            button: 'Registrasi untuk SPO',
            divider: 'Kill the middleman of necessity, push power to the edges and build systems that are equally fair for the least amongst us.',
            divider_p: '- French proverb',
        },
        roadmap: {
            head: 'Roadmap',
            divider: 'Life is better whit Pigs.',
            divider_p: '- Unknown',
            q1: {
                head: '$ Q1 - 2021',
                list_1: '',
            },
            q2: {
                head: '$ Q2 - 2021',
                list_1: 'Pengumuman Project ✓',
                list_2: 'Pembuatan White Paper ✓',
                list_3: 'Pemmbuatan Website ✓',
                list_4: 'Distribusi Token kepada para SPOs (In Progress)',
            },
            q3: {
                head: '$ Q3 - 2021',
                list_1: 'Listing di SWAP (DEX, CEX) ketika Alonzo fork diluncurkan',
                list_2: 'Mencari use-cases sebagai Oracle fee token',
                list_3: 'Pengumuman #PIGYGammes',
            },
            q4: {
                head: '$ Q4 - 2021',
                list_1: 'Launching #PIGYGames',
                list_2: 'Listing on Exchanges',
                list_3: 'Partnership Announcements',
            },
        },
        aboutus: {
            head: 'About us',
            text_1: 'Hello, kami dari PIGY Token tim ingin menceritakan sedikit mengenai latar belakang kami. Kami adalah stake pool operator yang kesulitan mencari delegator. Ini kemudian membuahkan ide untuk membuat PIGY Token sebagai incentive untuk para delegator agar mulai mendelegasikan ADA nya pada stake pool kecil. Kami mohon dukungannya. Terima kasih.',
            text_2: 'Apabila anda ingin menjadi bagian dari tim kami atau anda ingin menggunakan PIGY Token dalam project anda, anda dapat menghubungi kami melalui social media kami.',
        },
        social: {
            head: 'Social',
            text: 'Temukan social media channel kami. Komunitas Cardano sedang menanti anda!',
        },
        faq: {
            head: 'FAQ',
            question_1: 'Bagaimana cara saya mendapatkan $PIGY Token',
            answer_1: 'Hanya stake pool operators yang dapat ambil bagian dalam airdrop ini. Tanyakan kepada SPO and apakah mereka memiliki $PIGY Token!',
            question_2: 'Apakah PIGY Coin atau Token?',
            answer_2: 'PIGY Token adalah native token yang dibuat diatas Cardano blockchain. <a target="_blank" href="https://docs.cardano.org/native-tokens/learn">Link</a>',
            question_3: 'Saya adalah Stake Pool Operator bagaimana cara mengklaim PIGY Tokens?',
            answer_3: 'Pada saat ini kami belum dapat mendistribusikan token secara otomatis. Kami berencana menambah fitur ini pada saat Alonzo Hardfork. Pada Saat ini anda dapat meng-apply melalui form: <a target="_blank" href="https://tripetto.app/run/5ZQ50RRTIE">Register</a>',
            question_4: 'Saya adalah Stake Pool Operator berapakah biaya untuk mengklaim PIGY Token?',
            answer_4: 'Untuk membantu kami agar tidak membayar fee, kami akan meminta anda mengirim 2ADA ke alamat berikut. Anda akan mendapat 1.5 ADA dan PIGY Tokens. Untuk detailnya ada di form: <a target="_blank" href="https://tripetto.app/run/5ZQ50RRTIE">Register</a>',
            question_5: 'Apa itu PIGY Token?',
            answer_5: 'PIGY Token adalah Cardano based cryptocurrency yang di distrubusikan SPO sebagai additional rewards kepada delegators',
            question_6: 'Berapa banyak PIGY yang harus saya berikan kepada delegator?',
            answer_6: 'Kami saat ini tidak men-set berapa banyak PIGY yang kamu berikan kepada delegator. Sebagai bantuan kami menyediakan data statistik tiap epoch untuk setiap delegators yang dapat kalian temukan disini. <a target="_blank" href="https://statistics.pigytoken.com">Link</a>',
            question_7: 'Berapa lama saya menerima PIGY setelah saya mengisi form?',
            answer_7: 'Biasanya anda akan mendapatkan setelah 24 jam, kecuali Sabtu dan Minggu. Saat ini kami hanya mendistribusikan secara manual.',
            question_8: 'Apa yang terjadi setelah SPO Airdrop selesai?',
            answer_8: 'Pada awalnya untuk mendorong distribusi, kami akan mendistribusikan 25B Pigy Tokens kepada SPOs. Setelah itu, kami akan menggunakan analytics untuk memecahkan masalah distribusi. Pada saat itu kemungkinan lebih sedikit yang di distribusikan kepada SPOs.',
            question_9: 'Apakah kami akan mengembangkan lebih banyak service untuk PIGY Token?',
            answer_9: 'Iya. Kami berusaha keras untuk dapat mewujudkannya, Akan tetapi kita tetap harus menunggu Alonzo Hardfork terlaksana. Sambil menunggu, silahkan cek PIGY Image Game. <a target="_blank" href="https://genetics.pigytoken.com/">Genetics Game</a>',
            question_10: 'Anda ingin join PIGY Token Team?',
            answer_10: 'Kontak kami melalui channel berikut (Mail, Twitter, Discord, Telegram, Github)',
        },
        footer: {
            copyright: '© PIGYToken 2021. All Rights Reserved. ❤️ CARDANO.',
            disclaimer:
                'LEGAL DISCLAIMER: None of the information on this website should be construed as providing legal or financial advice. Please note there are always risks associated with Native Tokens and Smart contracts. Please use at your own risk. PIGYToken is not a registered broker, analyst or investment advisor. If you are willing to, or have purchased PIGYToken, you agree that you are not purchasing a security or investment. The PIGYToken team can not be held liable for any losses or taxes you may incur. You also agree that the team is presenting the token as it was launched, due to it being renounced it can not be changed. Do conduct your own due diligence and consult your financial advisor before making any investment decisions.',
        },
    },
    jp: {
        nav: {
            home: 'ホーム',
            whatispigy: 'PIGYとは',
            token: 'トークンエコノミー',
            spo: 'SPO',
            roadmap: 'ロード’マップ',
            faq: 'FAQ',
            aboutus: 'About us',
        },
        home: {
            head: 'SPO(ステークプールオペレーター)とデリゲーター(委任者)のためのミームトークン',
            text: '私たちはCardanoの分散化に貢献します。PIGY TokenはSPOから委任者へ、追加の報酬として配られるカルダノベースの暗号通貨です。',
            button: 'PIGYとは',
            button_buy: '購入する',
            divider: '豚は賢くてかわいい生き物です。愛を必要としています。',
            divider_p: '- シェリーデュバル',
        },
        whatispigy: {
            head: 'PIGY Tokenについて',
            text: 'PIGY Tokenはカルダノブロックチェーン上に作られた暗号通貨であり、SPOから委任者へ追加の報酬として配られます。PIGY Tokenは、カルダノの分散化と整合性の支えである小さなステークプールへの委任者をサポートすることによって、エコシステムを強化します。',
            text_2: 'カルダノとは、暗号通貨を生成・開発するプロセスを改良して2015年にローンチされた暗号通貨プロジェクトです。暗号通貨の発行方法を変えるだけにとどまらない、この壮大なアイデアは、包括的なロードマップ、徹底した設計原則、最善の工学的実践、ユーザーのニーズを適切に説明する手段などを通して、暗号通貨の世界によりすばらしい冗長的なエコシステムを形成します。現在、約2,600のステークプールがあります。その約30%のプールがまだ一度もブロックを生成したことがありません。カルダノ財団やIOGは、委任料が少ないプールの運営者が生き残るために最善を尽くしていますが、リソースは限られています。PIGY TokenはSPOから委任者へ配られるので、委任者は委任料の少ないプールにも委任してくれるようになります。私たちはこのようにして、まだブロック生成がないプールや委任料の少ないプールを支援していきたいと考えています。',
            button: 'ホワイトペーパーを見る',
            divider: 'ブタのしっぽは決して矢印にはならない.',
            divider_p: '- フランスのことわざ',
        },
        token: {
            head: 'トークンエコノミー',
            text_supply_head: '$ SUPPLY',
            text_supply:
            'PIGY Tokenは現在ロックされており、供給量は1000億トークンに限定しています。つまり今後、追加で生成されたりバーンされることはありません。つまり、トークンの無限供給によるインフレが起きないため、価格下落の防止になります。',
            text_distributor_head: '$ DISTRIBUTOR',
            text_distributor: 'PIGY TokenはあなたがADAを委任しているSPOから無料で受け取ることができます。規約が適用されます。.',
        text_buy_head: '$ BUY',
        text_buy: 'カルダノアロンゾメインネットが始動したら、PIGY Tokenをスワップし、取引所に上場します。最新の情報をこちらでお知らせします！',
        text_airdrop_head: '$ Token Airdrop',
        text_airdrop:
            '登録を済ませたSPOに2500万PIGY Tokensを配布しています。SPOの方は、フォームから申請していただくことで、PIGY Tokenを受け取ることができます。',
        divider: '‘ブタが口笛を吹いている気がする！',
        divider_p: '- ドイツのことわざ',
        },
        spo: {
            head: 'SPO',
            text: 'プールのティッカーを入力すると、PIGY Tokenを受け取っているプールを見つけることができます。PIGY Tokenの受け取り方は委任先のSPOにお尋ねください。.',
            notice: 'SPOの方はフォームにご記入ください。1プールにつき1000万PIGY Tokenをお送りします（1回限り）',
            notice2: 'tripetto.appにジャンプします’,
            button: 'SPOの方はこちら',
            divider: '中間業者を排除し、権力を追いやり、少なくとも私たちの間では等しく公平なシステムを構築します。',
            divider_p: '- チャールズホスキンソン',
            pool_count_text_1: 'Over ',
            pool_count_text_2: 'Stake Pools have now receive $PIGY Token.',
            pool_count_text_3: 'We have currently distributed ',
            pool_count_text_4: '$PIGY tokens to Stake Pool operators.',
        },
        roadmap: {
            head: 'ロードマップ',
            divider: 'ブタと共に過ごす人生はよりよい。',
            divider_p: '- 作者不明',
            q1: {
                head: '$ Q1 - 2021',
                list_1: '',
            },
            q2: {
                head: '$ Q2 - 2021',
                list_1: 'プロジェクトの告知 ✓',
                list_2: 'ホワイトペーパー作成 ✓',
                list_3: 'ホームページ作成 ✓',
                list_4: 'SPOへのトークン配布（進行中）',
            },
            q3: {
                head: '$ Q3 - 2021',
                list_1: 'DApps作成（Oracle Token） ✓',
                list_2: 'PIGY Oracle ✓',
                list_3: 'アロンゾハードフォーク後SWAP (DEX)上場',
            },
            q4: {
                head: '$ Q4 - 2021',
                list_1: '#PIGYGamesローンチ',
                list_2: '取引所に上場',
                list_3: 'パートナーシップ告知',
            },
        },
        aboutus: {
            head: 'About us',
            text_1: 'こんにちは！Piggysです！簡単な私たちの自己紹介をします。私たちがステークプールを運営し始めたころは、まだ委任量が少なく、委任を集めるのに苦労していました。そのことが、委任料が少ないプールでステーキングをしてもらえるようにしていくアイデアを思いつくきっかけとなりました。PIGY Tokenを支援することによって、カルダノの分散化に貢献することにも繋がります。',
            text_2: 'PIGY Tokenのアイデアは、最初はジョークとして生まれました。ドージコインのパロディであり（当初は名前をドージコインキラーにするつもりだった）カルダノブロックチェーン上で作ったミームトークンにすぎませんでした。しかしただのミームトークンは必要なく、価格変動のゲームのようなことはしたくないということに気付いたため、PIGY Tokenにより深い意味を持たせることにしました.',
            text_3: 'Pigy Tokenは発展のための第一フェーズであるカルダノフォーラムで最初の一歩を踏み出しました。SPOやプログラマーがいるコミュニティーでの反応がなかなかよかったので、はじめに小さなサービス(<a target="_blank" href="https://genetics.pigytoken.com/">Pigy Genetics</a>)とホームページを作りました。それからより一層成長し、どのようにSPOを助け、どうやってカルダノエコシステムの分散化に貢献していくか、すでにさらなる計画を立てています。',
            text_4: '私たちの活動に興味がある方や、ご自身のプロジェクトでPIGY Tokenを使いたいとお考えの方は、ソーシャルメディアからご連絡ください。',
        },
        social: {
            head: 'ソーシャル',
            text: 'PIGY Tokenのソーシャルメディアはこちらです。カルダノコミュニティーはあなたのご参加をお待ちしています！',
        },
        faq: {
            head: 'FAQ',
            question_1: '$PIGY tokenはどこでもらうことができますか？',
            answer_1: '現在PIGY TokenをエアドロップしているのはSPOだけです。委任先プールのSPOにお問い合わせください。',
            question_2: 'Pigyはコインですか？トークンですか？',
            answer_2: 'Pigy Tokenはカルダノブロックチェーン上のネイティブトークンです。 <a target="_blank" href="https://docs.cardano.org/native-tokens/learn">Link</a>',
            question_3: '私はSPOですが、どこでトークンを受け取ることができますか？',
            answer_3: '今はまだ自動でトークンを配布するシステムはありません。アロンゾハードフォーク後にシステムを構築する予定です。現在はこちらのフォームからの申請のみ受け付けています。: <a target="_blank" href="https://tripetto.app/run/5ZQ50RRTIE">Register</a>',
            question_4: '私はSPOですが、トークンを受け取る際、手数料はかかりますか？',
            answer_4: 'トランザクションフィーとして2ADAの送金をお願いします。PIGY Tokenを受け取る時に1.5ADAが戻ります。詳細はこちらで確認できます。: <a target="_blank" href="https://tripetto.app/run/5ZQ50RRTIE">Register</a>',
            question_5: 'PIGY ’Tokenとはなんですか？',
            answer_5: 'PIGY Tokenとは、SPOから委任者へ追加の報酬として配布されるカルダノベースの暗号通貨です。',
            question_6: '委任者にPIGY Tokenを何枚配布すればいいですか？',
            answer_6: '委任者にPIGY Tokenを何枚配布するか、私たちからの指定はありません。こちらのページでエポック毎に各プールの全委任者の統計を算出しているので参考にしてください。 <a target="_blank" href="https://statistics.pigytoken.com">Link</a>',
            question_7: 'フォーム入力後、PIGY Tokenを受け取るまで何日ほどかかりますか？',
            answer_7: '配布は手動で行っているため、通常はおよそ24時間以内に配布します。土日は除きます。',
            question_8: 'SPOへのエアドロップ終了後はどうなりますか？',
            answer_8: 'PIGY’ Token配布当初は、より多くをSPOに受け取ってもらうために250億PIGYを用意しました。その後は、サービスを介して分布を解析します。',
            question_9: '今後PIGY Tokenのサービスはさらに増えますか？',
            answer_9: 'はい。より多くのサービスを提供できるように準備しています。まずはこちらのlittle Pigy Image Gameをお楽しみください。 <a target="_blank" href="https://genetics.pigytoken.com/">Genetics Game</a>',
            question_10: 'Pigy Tokenのチームに参加したいのですが？',
            answer_10: 'メール、Twitter、Discord、Telegram、Githubのいずれかでお問い合わせください。',
        },
        footer: {
            copyright: '© PIGYToken 2021. All Rights Reserved. ❤️ CARDANO.',
            disclaimer:
                'LEGAL DISCLAIMER: このサイト上の情報は、法的あるいは財務的アドバイスを提供するものではありません。ネイティブトークンやスマートコントラクトには常にリスクが伴うことにご注意ください。すべてはご自身の責任の上でお願いいたします。PIGYTokenはブローカー、アナリスト、投資顧問ではありません。PIGY Tokenは証券や投資案件ではありません。PIGYTokenチームは、あなたが被る可能性のある損失または税金について責任を負わないものとします。また、トークンを放棄されても変更不可能であり、私たちチームはローンチされた状態でトークンを提供します。投資判断をする前には必ず適正な調査活動を行い、必要であればファイナンシャルアドバイザーにご相談することをお勧めします。’,
        },
    },
};
